# Generated by Django 2.2.19 on 2023-10-25 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photos', models.TextField()),
                ('release_date', models.DateField()),
                ('mileage', models.IntegerField()),
                ('engine_number', models.CharField(max_length=100)),
                ('advertisement_link', models.URLField()),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.Configuration')),
                ('drive_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.Drive')),
                ('transmission_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.Transmission')),
            ],
        ),
    ]
